# Generated by Django 4.2 on 2024-06-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericos.region')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericos.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('informacion_adicional', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericos.distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genericos.provincia')),
            ],
        ),
    ]
