# Generated by Django 4.2 on 2024-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
